### ISSUE TITLE
No Error but no Message received and no Id is found? 

### ISSUE THREAD

**Issue by DenisMtfl** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#46]
Hello im using the project in a C# Console Test (.NET 7.0), i have configurated the app in the developer tool and Access Token but when i send a message to my number the message isn't receied and also the BusinessId is not found from the NumberId ?
Can you help me to find the error? There is not Exception.

![image](https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net/assets/1503277/81cb46c4-2f98-47f8-8964-339d91bf5cdc)

**Comment by gabrieldwight** [comment]
Hi, the get business profile just returns the information about the business since it does not return businessid and phone number id. The business id is only available when you go live with a production phone number. To send a message you will only need phone number id and whatsapp business account id which you can find them from the developer portal.


If you are testing with the test phone number from meta you need to send a sample template message from its portal and reply with any text then you can send a message to your phone number.
![image](https://github.com/gabrieldwight/Whatsapp-Business-Cloud-Api-Net/assets/28096255/58909031-19c1-4ded-b473-7a1b3debb275)
