### ISSUE TITLE
Unable to edit Whatsapp Business Account subscription

### ISSUE THREAD

**Issue by SeraphsVII** [gabrieldwight/Whatsapp-Business-Cloud-Api-Net#5]
First of all thank you for this lib, it has been the most useful overall.

As of now I have not been able to setup the callback URL for the webhook, while testing the connection while the project runs on HTTPS localhost, i get the next error message:

The URL couldn't be validated. Callback verification failed with the following errors: curl_errno = 56; curl_error = Received HTTP code 403 from proxy after CONNECT; HTTP Status Code = 403; HTTP Message = Forbidden
![url](https://user-images.githubusercontent.com/37815566/180473288-ae11466d-dc21-4ff6-9dd8-bc4de747681a.png)

I have already checked time and time again my VerifyToken, WhatsAppBusinessPhoneNumberId, WhatsAppBusinessAccountId, WhatsAppBusinessId, AccessToken.

As of now i'm using .net core 6.0  

Any kind of help will be of great assistance and thank you in advance for your time.

**Comment by gabrieldwight** [comment]
@SeraphsVII You will need to expose your callback URL using an HTTP tunneling tool so it can be publicly accessible by WhatsApp Business. Since you are testing you can use the Conveyor tool to expose the localhost callback URL. You can install the [Conveyor Extension](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1448185.ConveyorbyKeyoti) since it will help you to send back the verification code to Facebook so it can activate and validate your webhook.

Let me know if that solves your issue?
